import dam from "./images/Damascus.avif";
import rkr from "./images/rkr.avif";
import jasm from "./images/jasm.avif";
import md from "./images/md.avif";
import eb from "./images/eb.avif";
import rose from "./images/rose.avif";
import hm from "./images/hm.webp";
import al from "./images/al.webp";
import port from "./images/port.webp";
import hb from "./images/hb.webp";

const Sdata2 = [
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Rat Ki Rani",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Madhumalti Dwarf",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Elephant Bush",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Hydrangea macrophylla",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: rose,
    name: "Aloevera",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: rose,
    name: "Portulaca",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: rose,
    name: "Hibiscus",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: rose,
    name: "Jasminum sambac",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },

  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: rose,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "indoor",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "ornamental",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
  {
    imgsrc: dam,
    name: "Damascus Rose",
    para: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus perspiciatis ratione consectetur perferendis, repellendus cupiditate nulla modi, nesciunt sapiente ipsum a magni incidunt!",
    price: 250,
    category: "exotic",
  },
];

export default Sdata2;
